BEGIN;

-- Insertion des zones de lieux
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (1, '30', '114260', 'AEROPORT D''ORLY (TERMINAL OUEST)', '5', 'Arrêt de bus', 1);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (2, '16829', '122086', 'HAUSSMANN - ST LAZARE', '', '', 2);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (3, '16827', '121643', 'GARE ST LAZARE', '', '', 2);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (4, '8012', '114148', 'LYCEE FLORA TRISTAN', '', '', 3);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (5, '2231', '110585', 'PETIT BICETRE', '', '', 4);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (6, '13304', '110102', 'CLEMATITES', '', '', 5);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (7, '110059', '123146', 'DOLET - ZOLA', '5', 'Arrêt de bus', 6);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (8, '450', '110640', 'CHATEAU D''EAU', '', '', 7);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (9, '13353', '110057', 'CHEMIN DE VARENNES', '', '', 7);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (10, '13352', '110259', 'FOLLE AVOINE', '', '', 7);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (11, '13301', '110129', 'CHATAIGNIERS', '', '', 8);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (12, '3642', '110520', 'MESSIDOR - LIBERTE', '', '', 9);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (13, '13295', '110613', 'CES GEORGES BRASSENS', '', '', 10);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (14, '2312', '116398', 'PLACE DES FETES', '', '', 11);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (15, '2717', '112107', 'ST MAUR - CRETEIL', '', '', 12);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (16, '1083', '112019', 'RUEIL MALMAISON', '', '', 13);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (17, '7973', '113539', 'MAIRIE', '', '', 14);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (18, '1677', '110426', 'RESIDENCE DU PARC', '', '', 15);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (19, '13294', '110093', 'CEDRES BLEUS', '', '', 16);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (20, '2871', '116459', 'TOURNELLES DE PAMPHOU', '', '', 16);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (21, '7988', '113727', 'CORPS DE GARDE', '', '', 17);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (22, '2447', '114739', 'PORTE MAILLOT', '', '', 18);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (23, '11313', '119784', 'LES 7 ARBRES', '', '', 19);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (24, '2779', '114210', 'ST DONAIN', '', '', 20);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (25, '2459', '110413', 'POSTE', '', '', 21);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (26, '3306', '121404', 'ABBE GROULT', '', '', 22);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (27, '366', '116469', 'CENTRE COMMERCIAL PASTEUR', '', '', 23);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (28, '1627', '110650', 'LES CHENES', '', '', 23);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (29, '287', '121385', 'VAUGIRARD - CAMBRONNE', '', '', 24);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (30, '15674', '113982', 'LES PRAILLONS', '', '', 25);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (31, '110073', '123131', 'CAMELIAS', '', '', 26);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (32, '2999', '114242', 'ZONE INDUSTRIELLE DE LA BORNE BLANCHE', '', '', 27);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (33, '110067', '122928', 'REPUBLIQUE - BLUM', '5', 'Arrêt de bus', 28);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (34, '7989', '113737', 'PLACE DU CALVAIRE', '', '', 29);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (35, '162', '117390', 'BEAU - MENDES FRANCE', '', '', 30);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (36, '7990', '113746', '4 CHEMINS', '', '', 31);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (37, '1054', '114139', 'GARE ROUTIERE', '3', 'Gare routière', 32);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (38, '2616', '109656', 'ROUTE DE BUCHELAY', '', '', 33);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (39, '11312', '119806', 'PAUL BERT', '', '', 34);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (40, '16892', '119664', 'BOULEY - ECOLE VETERINAIRE', '', '', 35);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (41, '760', '122766', 'ECOLE VETERINAIRE DE MAISONS ALFORT', '5', 'Arrêt de bus', 35);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (42, '5881', '112217', 'NEUVILLE UNIVERSITE', '', '', 36);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (43, '13345', '110463', 'YVERNY', '', '', 37);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (44, '3278', '120678', 'BALARD', '', '', 38);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (45, '8349', '122946', 'PLANETES', '5', 'Arrêt de bus', 39);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (46, '622', '121394', 'CONVENTION', '', '', 40);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (47, '1864', '110331', 'MAIRIE', '', '', 41);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (48, '16471', '110304', 'CENTRE HOSPITALIER DE BRIE COMTE ROBERT', '', '', 42);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (49, '10196', '123081', 'RUE DE MARSEILLE', '5', 'Arrêt de bus', 43);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (50, '7971', '113521', 'BAS', '', '', 44);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (51, '2091', '116442', 'MOULIN FLEURI', '', '', 45);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (52, '7972', '113530', 'BRIOTTE', '', '', 46);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (53, '3636', '122848', 'COLLEGE GUYARD', '5', 'Arrêt de bus', 47);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (54, '2798', '114827', 'ST PAUL', '', '', 48);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (55, '110051', '123066', 'MAIRIE DE MAISONS-ALFORT', '5', 'Arrêt de bus', 49);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (56, '16472', '110435', 'TRAIN DES ROSES', '', '', 50);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (57, '1192', '110683', 'CLEMENCEAU', '', '', 51);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (58, '9120', '123042', 'LOUIS FLICHE', '5', 'Arrêt de bus', 52);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (59, '16518', '112239', 'CHAMPIGNY', '', '', 53);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (60, '13355', '110080', 'C.CIAL DES QUATRE VENTS', '', '', 54);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (61, '9272', '122978', 'RUE DE LILLE', '5', 'Arrêt de bus', 55);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (62, '17070', '112140', 'SUCY BONNEUIL', '', '', 56);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (63, '3659', '120813', 'GARE ROUTIERE DE VILLENEUVE ST GEORGES', '3', 'Gare routière', 57);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (64, '2984', '121428', 'VILLENEUVE ST GEORGES', '1', 'Gare ferrée', 57);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (65, '7975', '113557', 'EGLISE', '', '', 58);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (66, '662', '114112', 'CROIX DE LA MISSION', '', '', 59);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (67, '3489', '123478', 'SAULES - CORTOT / LES VIGNES', '5', 'Arrêt de bus', 60);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (68, '3474', '123296', 'ABREUVOIR GIRARCON', '5', 'Arrêt de bus', 60);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (69, '16860', '123228', 'MONT CENIS - CORTOT', '5', 'Arrêt de bus', 60);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (70, '7981', '113626', 'EGLISE', '', '', 61);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (71, '8002', '113901', 'PLACE ROUTE NATIONALE', '', '', 62);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (72, '1023', '114274', 'GARE DE L''EST', '1', 'Gare ferrée', 63);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (73, '2413', '113755', 'PORT MONTAIN', '', '', 64);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (74, '1067', '114281', 'PANTIN', '1', 'Gare ferrée', 65);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (75, '8000', '113876', 'COUTURE', '', '', 66);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (76, '109299', '114175', 'Compigny', '5', 'Arrêt de bus', 67);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (77, '154', '114871', 'BASTILLE', '', '', 68);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (78, '7982', '113637', 'CAFE', '', '', 69);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (79, '7980', '113612', 'MAIRIE', '', '', 70);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (80, '7979', '113601', 'EGLISE', '', '', 71);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (81, '676', '123255', 'CUSTINE - RAMEY', '5', 'Arrêt de bus', 72);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (82, '2935', '116533', 'VICTOR HUGO', '', '', 73);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (83, '2569', '123496', 'ROCHECHOUART - MARTYRS', '5', 'Arrêt de bus', 74);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (84, '3512', '123278', 'ORSEL', '5', 'Arrêt de bus', 74);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (85, '7977', '113576', 'AVIGNY', '', '', 75);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (86, '834', '114673', 'ESPLANADE DE LA DEFENSE', '', '', 76);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (87, '3088', '122075', 'TRINITE - D''ESTIENNE D''ORVES', '', '', 77);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (88, '13322', '110548', 'LYCEE AGRICOLE - RD 319', '', '', 78);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (89, '8003', '113921', 'BOULANGERIE', '', '', 79);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (90, '79', '114684', 'ARGENTINE', '', '', 80);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (91, '8001', '113890', 'MOULIN OCLE', '', '', 81);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (92, '4254', '120740', 'POLYCLINIQUE', '', '', 82);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (93, '15676', '114233', 'CAMPING', '', '', 83);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (94, '14636', '120797', 'PONT D''YERRES - CONSERVATOIRE', '', '', 84);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (95, '1032', '111986', 'LA VARENNE CHENNEVIERES', '', '', 85);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (96, '2539', '123054', 'REPUBLIQUE - GENERAL LECLERC', '5', 'Arrêt de bus', 86);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (97, '2112', '111909', 'NOISIEL', '', '', 87);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (98, '5937', '112096', 'ACHERES GRAND CORMIER', '', '', 88);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (99, '3488', '123487', 'LAMARCK - BECQUEREL', '5', 'Arrêt de bus', 89);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (100, '13306', '110322', 'DR LAENNEC', '', '', 90);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (101, '13318', '110221', 'JULES FERRY', '', '', 91);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (102, '3491', '123265', 'CUSTINE - MONT CENIS', '5', 'Arrêt de bus', 92);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (103, '3492', '123219', 'LAMARCK - MONT CENIS', '5', 'Arrêt de bus', 92);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (104, '13363', '110453', 'TRANCART', '', '', 93);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (105, '1507', '123438', 'LAMARCK - CAULAINCOURT', '5', 'Arrêt de bus', 94);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (106, '13326', '110340', 'MILLET', '', '', 95);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (107, '16470', '110212', 'ERIK SATIE', '', '', 96);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (108, '3490', '123287', 'MARCADET', '5', 'Arrêt de bus', 97);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (109, '1243', '116415', 'GYMNASE', '', '', 98);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (110, '5892', '112129', 'NOGENT SUR MARNE', '', '', 99);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (111, '5908', '111942', 'CERGY - ST CHRISTOPHE', '', '', 100);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (112, '1045', '109684', 'MANTES LA JOLIE', '', '', 101);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (113, '1147', '109698', 'GARE ROUTIERE', '3', 'Gare routière', 101);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (114, '1977', '123091', 'MAISONS ALFORT LES JUILLIOTTES', '5', 'Arrêt de bus', 102);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (115, '3481', '123314', 'FUNICULAIRE MONTMARTRE STATION HAUTE', '5', 'Arrêt de bus', 103);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (116, '10088', '123210', 'UTRILLO', '5', 'Arrêt de bus', 103);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (117, '3487', '123414', 'CHEVALIER DE LA BARRE', '', '', 103);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (118, '1038', '112008', 'LOGNES', '', '', 104);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (119, '1135', '112041', 'PARC DE ST MAUR', '', '', 105);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (120, '55', '117386', 'AMBROISE PARE', '', '', 106);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (121, '973', '112228', 'BOISSY ST LEGER', '', '', 107);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (122, '5894', '110480', 'GARE ROUTIERE', '3', 'Gare routière', 107);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (123, '1020', '112272', 'JOINVILLE LE PONT', '', '', 108);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (124, '3484', '123460', 'CHAPPE', '5', 'Arrêt de bus', 109);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (125, '3485', '123246', 'YVONNE LE TAC', '5', 'Arrêt de bus', 109);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (126, '521', '110665', 'CLAUDE BERNARD', '', '', 110);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (127, '13362', '110272', 'LA FONTAINE', '', '', 111);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (128, '550', '110716', 'CES A.CHAUSSY', '', '', 112);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (129, '1105', '112151', 'TORCY', '', '', 113);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (130, '4542', '122327', 'PALISSY', '', '', 114);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (131, '9014', '123024', 'JOUET', '5', 'Arrêt de bus', 115);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (132, '13315', '110506', 'HAIE GRISELLE', '', '', 116);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (133, '110000', '122290', 'GARE DE PUTEAUX', '5', 'Arrêt de bus', 117);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (134, '1396', '123424', 'JULES JOFFRIN', '5', 'Arrêt de bus', 118);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (135, '1744', '114130', 'LYCEE ANDRE MALRAUX', '', '', 119);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (136, '3647', '122990', 'RENE COTY', '5', 'Arrêt de bus', 120);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (137, '2552', '114717', 'REUILLY - DIDEROT', '', '', 121);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (138, '2847', '109646', 'GARE ROUTIERE - TERMINAL JULES VERNE', '3', 'Gare routière', 122);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (139, '1443', '112118', 'LA DEFENSE', '', '', 122);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (140, '1111', '112349', 'VAL D EUROPE', '', '', 123);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (141, '5911', '112195', 'VAL DE FONTENAY', '', '', 124);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (142, '7974', '113548', 'VILLIERS SUR TERRE', '', '', 125);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (143, '2960', '114002', 'VILLE HAUTE', '', '', 126);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (144, '2442', '114783', 'PORTE DE VINCENNES', '', '', 127);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (145, '16861', '123364', 'TOURLAQUE', '5', 'Arrêt de bus', 128);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (146, '1144', '114012', 'GARE ROUTIERE', '3', 'Gare routière', 129);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (147, '901', '114761', 'FRANKLIN ROOSVELT', '', '', 130);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (148, '8007', '114031', 'FOYER', '', '', 131);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (149, '1807', '122064', 'MADELEINE', '', '', 132);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (150, '2773', '123516', 'ST AUGUSTIN', '', '', 133);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (151, '3477', '123382', 'MOULIN DE LA GALLETE / RUE LEPIC No88', '5', 'Arrêt de bus', 134);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (152, '1256', '122702', 'HAVRE - HAUSSMANN', '', '', 135);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (153, '16986', '122214', 'HAVRE - CAUMARTIN', '', '', 135);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (154, '11948', '112338', 'CHATOU - CROISSY', '', '', 136);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (155, '386', '114166', 'CFA DE ST GERMAIN', '', '', 137);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (156, '15671', '113810', 'MAIRIE', '', '', 138);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (157, '1043', '112316', 'MAISONS LAFFITTE', '', '', 139);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (158, '5223', '114904', 'ST MANDE', '', '', 140);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (159, '1124', '112162', 'VINCENNES', '', '', 141);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (160, '184', '114816', 'BERAULT', '', '', 142);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (161, '8005', '113946', 'PARKING', '', '', 143);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (162, '16859', '123391', 'GABRIELLE', '5', 'Arrêt de bus', 144);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (163, '3486', '123401', 'PLACE DU TERTRE - NORVINS', '5', 'Arrêt de bus', 144);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (164, '3483', '123237', 'DREVET', '5', 'Arrêt de bus', 144);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (165, '15668', '113494', 'VERNOY', '', '', 145);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (166, '3478', '123373', 'DURANTIN - BURQ', '5', 'Arrêt de bus', 146);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (167, '3479', '123305', 'THOLOZE', '5', 'Arrêt de bus', 146);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (168, '15675', '114220', 'CARRASCO', '', '', 147);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (169, '7994', '113800', 'VIEUX PONT', '', '', 147);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (170, '7987', '113717', 'PLACE MEROT', '', '', 148);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (171, '1140', '112085', 'MARNE LA VALLEE - CHESSY', '', '', 149);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (172, '452', '114772', 'CHATEAU DE VINCENNES', '', '', 150);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (173, '15670', '113782', 'TOUSSACQ', '', '', 151);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (174, '2428', '114267', 'PORTE DE CLICHY', '1', 'Gare ferrée', 152);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (175, '8009', '114054', 'GARE FLAMBOIN', '', '', 153);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (176, '13356', '110376', 'GRAND NOYER', '', '', 154);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (177, '538', '110698', 'CLOS DIDIER', '', '', 155);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (178, '13358', '110152', 'CHOPIN', '', '', 155);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (179, '13299', '110111', 'CHAPERONS 2', '', '', 156);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (180, '3634', '122958', 'GABRIEL PERI', '5', 'Arrêt de bus', 157);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (181, '941', '114253', 'AEROPORT CDG 2 TGV (TERMINAL 2)', '1', 'Gare ferrée', 158);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (182, '2393', '118799', 'PONT DE NEUILLY - RIVE DROITE', '', '', 159);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (183, '8008', '114044', 'FLAMBOIN 3 CHEMINS', '', '', 160);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (184, '1283', '109670', 'HOPITAL QUESNAY', '', '', 161);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (185, '17066', '111876', 'POISSY', '', '', 162);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (186, '1418', '121710', 'MIROMESNIL', '', '', 163);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (187, '2030', '121729', 'MATIGNON - ST HONORE', '', '', 163);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (188, '2057', '121720', 'HAUSSMANN - MIROMESNIL', '', '', 163);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (189, '17032', '114750', 'CHARLES DE GAULLE ETOILE', '', '', 164);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (190, '3809', '112030', 'CHARLES DE GAULLE ETOILE', '', '', 164);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (191, '7998', '113848', 'SILO', '', '', 165);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (192, '15669', '113503', 'PLACE DE L''ETOILE', '', '', 166);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (193, '2263', '116480', 'PISCINE', '', '', 167);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (194, '5214', '112305', 'FONTENAY SOUS BOIS', '', '', 168);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (195, '8004', '113932', 'LE VERGER', '', '', 169);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (196, '13307', '110367', 'DR ROUX', '', '', 170);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (197, '985', '112052', 'BUSSY ST GEORGES', '', '', 171);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (198, '13360', '110349', 'LES GRANDS MOULINS', '', '', 172);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (199, '1954', '122343', 'MAIRIE - ANATOLE FRANCE', '', '', 173);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (200, '21', '123342', 'ABBESSES', '5', 'Arrêt de bus', 174);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (201, '1189', '114662', 'GEORGE V', '', '', 175);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (202, '8013', '114186', 'LA GOUJONNE', '', '', 176);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (203, '961', '112184', 'HOUILLES - CARRIERES SUR SEINE', '', '', 177);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (204, '7995', '113820', 'GRAND PEUGNY', '', '', 178);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (205, '103', '121773', 'OPERA', '', '', 179);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (206, '2131', '121759', 'OPERA - 4 SEPTEMBRE', '', '', 179);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (207, '16831', '122710', 'OPERA - SCRIBE', '5', 'Arrêt de bus', 179);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (208, '982', '112206', 'BRY SUR MARNE', '', '', 180);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (209, '7999', '113862', 'ST SAUVEUR', '', '', 181);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (210, '1929', '114103', 'MAIRIE', '', '', 182);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (211, '501', '114121', 'CIMETIERE', '', '', 183);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (212, '7983', '113648', 'ST FIACRE', '', '', 184);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (213, '2309', '113690', 'PLACE DES BUTTES', '', '', 185);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (214, '1064', '111964', 'NOISY LE GRAND MONT D''EST', '', '', 186);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (215, '7993', '113791', 'TERRAIN DE BOULES', '', '', 187);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (216, '1058', '112063', 'NANTERRE PREFECTURE', '', '', 188);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (217, '3587', '114915', 'TUILERIES', '', '', 189);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (218, '4222', '122917', 'CECILE', '5', 'Arrêt de bus', 190);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (219, '1976', '123014', 'MAISON ALFORT - STADE', '5', 'Arrêt de bus', 190);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (220, '8890', '122754', 'CIMETIERE PARISIEN', '5', 'Arrêt de bus', 191);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (221, '15672', '113911', 'LES AULINS', '', '', 192);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (222, '2113', '112294', 'NOISY CHAMPS', '', '', 193);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (223, '7992', '113773', 'MAIRIE - ECOLE', '', '', 194);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (224, '1794', '114157', 'LEP GUSTAVE EIFFEL', '', '', 195);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (225, '16848', '114728', 'GARE DE LYON - DIDEROT', '', '', 196);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (226, '1041', '112250', 'GARE DE LYON', '', '', 196);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (227, '109800', '123101', 'GARE DE MAISONS ALFORT ALFORTVILLE', '5', 'Arrêt de bus', 197);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (228, '1042', '122736', 'MAISONS ALFORT ALFORTVILLE', '5', 'Arrêt de bus', 197);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (229, '1296', '114794', 'HOTEL DE VILLE', '', '', 198);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (230, '10195', '122968', 'COLLEGE DE STAEL', '5', 'Arrêt de bus', 199);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (231, '2560', '114849', 'LOUVRE - RIVOLI', '', '', 200);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (232, '1060', '122300', 'NANTERRE VILLE', '', '', 201);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (233, '2978', '121417', 'VOLONTAIRES - LECOURBE', '', '', 202);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (234, '1095', '112360', 'ST GERMAIN EN LAYE', '', '', 203);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (235, '4540', '122375', 'OFFENBACH', '1', 'Gare ferrée', 204);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (236, '1078', '122317', 'PUTEAUX', '', '', 204);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (237, '15673', '113971', 'TACHY', '', '', 205);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (238, '1059', '112283', 'NANTERRE UNIVERSITE', '', '', 206);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (239, '8809', '123032', 'HUGO-BLUM', '5', 'Arrêt de bus', 207);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (240, '7997', '113838', 'NEUVRY', '', '', 208);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (241, '7996', '113829', 'PETIT PEUGNY', '', '', 209);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (242, '15737', '116403', 'GALILEE', '', '', 210);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (243, '109848', '120700', 'Maisons-Alfort-Les Juilliottes', '2', 'Station de métro', 211);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (244, '1251', '114021', 'GOUAIX HAUT', '', '', 212);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (245, '8355', '123002', 'PONT DE MAISONS ALFORT', '5', 'Arrêt de bus', 213);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (246, '2811', '110534', 'STADE DE BONNEUIL', '', '', 214);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (247, '986', '112173', 'CERGY LE HAUT', '', '', 215);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (248, '2104', '111920', 'NATION', '', '', 216);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (249, '17000', '114695', 'NATION - PLACE DES ANTILLES', '', '', 216);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (250, '13349', '110599', 'ZI BORDE', '', '', 217);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (251, '2993', '110627', 'ZI CHARLES DE GAULLE', '', '', 217);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (252, '1237', '116392', 'GUSTAVE EIFFEL', '', '', 218);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (253, '844', '122047', 'EUROPE', '', '', 219);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (254, '2258', '123469', 'PIGALLE', '5', 'Arrêt de bus', 220);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (255, '1138', '111997', 'VESINET LE PECQ', '', '', 221);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (256, '13357', '110047', 'BERLIOZ', '', '', 222);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (257, '13359', '110120', 'CHAPERONS 3', '', '', 223);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (258, '2473', '111898', 'CERGY - PREFECTURE / GARE ROUTIERE', '', '', 224);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (259, '7978', '113587', 'MAIRIE', '', '', 225);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (260, '1692', '114882', 'LES SABLONS', '', '', 226);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (261, '7976', '113566', 'CIMETIERE', '', '', 227);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (262, '7986', '113704', 'COLLEGE JEAN ROSTAND', '', '', 228);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (263, '13308', '110313', 'PARKING HYPER U', '', '', 229);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (264, '7970', '113512', 'MAIRIE - ECOLE', '', '', 230);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (265, '11949', '111887', 'LE VESINET CENTRE', '', '', 231);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (266, '3020', '111953', 'CHATELET LES HALLES', '', '', 232);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (267, '7984', '113662', 'ECOLE', '', '', 233);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (268, '110077', '123154', 'MAISONS-ALFORT - ALFORTVILLE RER', '', '', 234);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (269, '7985', '113676', 'CIMETIERE', '', '', 235);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (270, '2977', '121376', 'VOLONTAIRES - VAUGIRARD', '', '', 236);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (271, '3599', '114805', 'CONCORDE', '', '', 237);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (272, '400', '114893', 'CHAMPS ELYSEES - CLEMENCEAU', '', '', 238);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (273, '997', '111975', 'CONFLANS FIN D OISE', '', '', 239);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (274, '5919', '112074', 'ACHERES VILLE', '', '', 240);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (275, '1088', '112371', 'SARTROUVILLE', '', '', 241);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (276, '8010', '114079', 'LES CHAISES', '', '', 242);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (277, '785', '114068', 'EGLISE', '', '', 243);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (278, '8014', '114197', 'ECLUSE', '', '', 244);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (279, '8006', '113957', 'MAIRIE', '', '', 245);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (280, '3810', '112327', 'AUBER', '', '', 246);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (281, '8323', '119673', 'PIERRE CURIE', '', '', 247);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (282, '2149', '114651', 'PALAIS ROYAL / MUSEE DU LOUVRE / COMEDIE FRANCAISE', '', '', 248);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (283, '8011', '114090', 'TOURY', '', '', 249);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (284, '1061', '112261', 'NEUILLY PLAISANCE', '', '', 250);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (285, '7969', '113485', 'MAIRIE', '', '', 251);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (286, '7991', '113764', 'OUINOTTE', '', '', 252);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (287, '286', '121367', 'CAMBRONNE - LECOURBE', '', '', 253);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (288, '457', '114706', 'CHATELET', '', '', 254);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (289, '1039', '113992', 'GARE ROUTIERE', '3', 'Gare routière', 255);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (290, '109336', '114838', 'La Défense (Grande Arche)', '2', 'Station de métro', NULL);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (291, '109757', '119826', 'ECOLE VETERINAIRE DE MAISONS-ALFORT-METRO', '5', 'Arrêt de bus', NULL);
INSERT INTO reflex_zone_de_lieu (id, id_ref_a, id_version, nom, id_type_arret, libelle_type_arret, reflex_lieu_d_arret_id) VALUES (292, '110136', '123639', 'test scission', '', '', NULL);

COMMIT;